### ISSUE TITLE
document.writeln vs console.log

### ISSUE THREAD

**Issue by bencooling** [ahfarmer/webpack-hmr-3-ways#1]
Thanks @ahfarmer for your posts and repos.

You mention in the [source code](https://github.com/ahfarmer/webpack-hmr-3-ways/blob/master/server-api/js/index.js)
`// console.log statements are reprinted on every reload.`

Can you explain if I replace console.log with document.writeln it doesn't reload?

**Comment by andrewagain** [comment]
Hmmm, I don't think `document.writeln` will work with HMR. 

 `document.writeln` doesn't work after the document is finished writing. HMR works by updating JavaScript without a reload, which means the document will always be finished loading.

I think this [StackOverflow post](http://stackoverflow.com/questions/24297829/execute-write-on-doc-it-isnt-possible-to-write-into-a-document-from-an-asynchr) might help.

You probably want something like [browserSync](https://www.browsersync.io/). It will reload the entire webpage whenever you make changes.

An even better option would be to abandon `document.writeln` in favor of DOM manipulations like [createElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement) and [appendChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild).

**Comment by bencooling** [comment]
👍🏼Legend thanks heaps. I didn't particularly need `document.writeln` but it tripped me up as I thought I didn't have HMR working until I finally decided to use a console.log after reading over your source code. Thanks again.
