### ISSUE TITLE
What's the best way to prevent the middleware approach from running in production?

### ISSUE THREAD

**Issue by nachocab** [ahfarmer/webpack-hmr-3-ways#3]
Should I detect `NODE_ENV` and run the middleware conditionally? Something like this:

```javascript
if (process.env.NODE_ENV != 'production') {
  app.use(webpackDevMiddleware);
  app.use(webpackHotMiddleware);
}
```
Or is there a better approach?

**Comment by andrewagain** [comment]
Hey @nachocab - great question. I didn't have production in mind with this approach. I've needed my development server to do multiple things in the past - that's where the webpack middleware works great.

Does your JavaScript code change in production? If not, you probably want to build it to a static file and serve that file - and not run Webpack in production at all.
